theme: jekyll-theme-cayman
title: welcome to the TextSLAM's homepage!
show_downloads: true ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: test [Your Google Analytics tracking ID]
